name: .NET Core Container Build and ACR Push

on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout the repo
        uses: actions/checkout@v3

      # Log in to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Log in to Azure Container Registry (ACR)
      - name: ACR Login with Azure CLI
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'  # Adjust as needed

      # Build and publish container image
      - name: Build and Push Container to ACR
        run: |
          ACR_LOGIN_SERVER="${{ secrets.ACR_NAME }}.azurecr.io"
          dotnet publish --os linux --arch x64 -c Release -p:PublishProfile=DefaultContainer \
            -p:ContainerRegistry=$ACR_LOGIN_SERVER \
            -p:ContainerImageTags=latest

      # Log out from Azure
      - name: Logout
        run: |
          az logout
